### ISSUE TITLE
Quest - Category 관계 수정

### ISSUE THREAD

**Issue by blupine** [bbolab/gaonna-backend#25]
<img width="1231" alt="스크린샷 2021-05-26 오후 8 42 08" src="https://user-images.githubusercontent.com/30730212/119653987-ed2aa700-be62-11eb-802b-f072fdc5f909.png">

Quest-Category가 현재 ManyToOne 관계인데, ManyToMany 관계가 되어야 하는게 맞지 않나요?

ex) 여러 퀘스트들이 동일한 카테고리를 갖는 케이스

그리고 Quest가 CategoryValue와 관계를 맺는게 아니라, Category와 맺는 것은 어떨까요?

key가 아닌 value에 의존하는게 좀 이상한 구조같습니다.

검토 후에 assign 해주십쇼

**Comment by sokdak** [comment]
Category는 실제적으로 의미가 있는 CategoryValue들을 grouping 하는 역할로 사용됩니다.
그렇기에, 실제적으로 의미가 있는 Value와 Quest 테이블을 Mapping 하는 것이 옳다고 판단되어지네요.

추가적으로 CategoryValue는 Quest와 N:M 관계가 되는것이 맞습니다. 수정이 필요하겠네요.
