### ISSUE TITLE
Quest - Article 분리

### ISSUE THREAD

**Issue by blupine** [bbolab/gaonna-backend#29]
현재는 Quest가 Article과 1대1 관계를 맺고 Article에 특징적인건 Article 엔티티에 값을 두고 있는데,

이럴 경우 일반 게시물을 조회할 때 마다 Quest와 관계가 없는(null) Article만 뽑아야 하는데, 이런 부분이 비용적으로 괜찮을지?

Quest에 Quest 필드들과, Article 필드를 그냥 한번에 두는 것은 안되는지??
-> Quest의 일부 게시물 관련 필드들은 Article의 필드들과 중복되는 문제가 있을수는 있음

**Comment by blupine** [comment]
Quest에 대해서 댓글, 좋아요같은 Article 특징적인 요청을 하게될 경우 Quest 컨트롤러에서 해야하는지, Article 컨트롤러에서 해야하는지?

- Quest 컨트롤러에서 하게될 경우
   - Article 컨트롤러에도 Article에 대해 댓글, 좋아요 처리 로직이 중복으로 생김
- Article 컨트롤러에서 하게될 경우
   - Quest 컨트롤러에는 퀘스트 조회, 업데이트 요청을, Article 컨트롤러에는 댓글 좋아요 요청
   - front 단에서는 api endpoint가 바뀜
   - Quest에 대한 Article 특징(제목, 내용)은 Quest 컨트롤러에 요청하면서, 왜 댓글 좋아요는 Article 컨트롤러를 통하나..

**Comment by sokdak** [comment]
Quest가 Article 필드를 가지게 될 경우, 기존 Article 엔티티가 제공하는 기능을 Quest에서도 제공하기 위해 Comment 및 Like 관계테이블이 추가되어야 합니다.
이러한 중복을 제거하기 위해 Quest Article 간 One-to-One으로 정규화 된 내용입니다.

더 좋은 방안이 있을까요?

**Comment by sokdak** [comment]
> Quest에 대해서 댓글, 좋아요같은 Article 특징적인 요청을 하게될 경우 Quest 컨트롤러에서 해야하는지, Article 컨트롤러에서 해야하는지?
> 
> * Quest 컨트롤러에서 하게될 경우
>   
>   * Article 컨트롤러에도 Article에 대해 댓글, 좋아요 처리 로직이 중복으로 생김
> * Article 컨트롤러에서 하게될 경우
>   
>   * Quest 컨트롤러에는 퀘스트 조회, 업데이트 요청을, Article 컨트롤러에는 댓글 좋아요 요청
>   * front 단에서는 api endpoint가 바뀜
>   * Quest에 대한 Article 특징(제목, 내용)은 Quest 컨트롤러에 요청하면서, 왜 댓글 좋아요는 Article 컨트롤러를 통하나..

Quest와 Article에 대한 CRUD URI가 같아야 할 필요는 없구요,
comment의 의미는 article에 대한 데이터가 있어야 의미가 있을 것 같다고 생각이 들어요. 
permalink가 필요하다면, `/article/{articleId}/comment/{commentId}` 가 되는것이 맞다고 생각됩니다.

**Comment by blupine** [comment]
의견 반영해서 엔드포인트 수정하겠읍니다.

**Comment by blupine** [comment]
@sokdak 
아래 커밋으로 해당 내용 반영했습니다.
https://github.com/bbolab/gaonna-backend/pull/31/commits/ddc29ab38b8803691ff2e9579e6661d612d205a8
