### ISSUE TITLE
Article 조회 기준

### ISSUE THREAD

**Issue by blupine** [bbolab/gaonna-backend#30]
Article 리스트는 어떤 파라미터를 받아서 조회해야하죠? 카테고리?

**Comment by blupine** [comment]
Article 엔티티에 필드 추가 필요(게시판 종류)

**Comment by sokdak** [comment]
자유게시판 조회: `SELECT * FROM article WHERE type='freeboard'`
이런 형태가 되어야 하지 않을까 하네요.

**Comment by blupine** [comment]
게시판 종류(ex.자유게시판, 공지사항) 어떤게 있을까요 @

**Comment by blupine** [comment]
enum타입으로 일단 현재 생각나는거만 올리겠습니다.
